export const WHITE = '#FFFFFF'
export const BLACK = '#000000'
export const GRADIENT_LOW = '#00D1FF'
export const GRADIENT_HIGH = '#006DFF'
export const DIMMED_BLUE = '#00D1FF'
export const GOOGLE_ORANGE = '#DD4B39'
